# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:title.html
relative_permalinks: true

# Setup
title:               El rincón de mautemático
tagline:             Las Cosas son como deben, no como deberían Ser.
url:                 https://jekyll.mautematico.com
paginate:            1
baseurl:             https://jekyll.mautematico.com

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mauricio Navarro Miranda
  url:               https://twitter.com/mautematico
  email:             mauricio@navarromiranda.mx

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/mautematico/blog

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
